// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lHDOGzYI1WpA9pdpk20QUXPnSoGGk1s',
    appId: '1:634763022031:web:03ad5345efe731d672f1ba',
    messagingSenderId: '634763022031',
    projectId: 'riverpod-auth-6c4e3',
    authDomain: 'riverpod-auth-6c4e3.firebaseapp.com',
    storageBucket: 'riverpod-auth-6c4e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bWb0HRy9xqfuMbMAI01YKndRPKtgayc',
    appId: '1:634763022031:android:8a4d5ba3db3c684b72f1ba',
    messagingSenderId: '634763022031',
    projectId: 'riverpod-auth-6c4e3',
    storageBucket: 'riverpod-auth-6c4e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjE3M1WDvC1zHkrQrJhS_iv10bEoFyJDY',
    appId: '1:634763022031:ios:1a4338f5229e262072f1ba',
    messagingSenderId: '634763022031',
    projectId: 'riverpod-auth-6c4e3',
    storageBucket: 'riverpod-auth-6c4e3.appspot.com',
    iosBundleId: 'com.example.authRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjE3M1WDvC1zHkrQrJhS_iv10bEoFyJDY',
    appId: '1:634763022031:ios:9bad136cda80ed6e72f1ba',
    messagingSenderId: '634763022031',
    projectId: 'riverpod-auth-6c4e3',
    storageBucket: 'riverpod-auth-6c4e3.appspot.com',
    iosBundleId: 'com.example.authRiverpod.RunnerTests',
  );
}
